import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDF = ({
  data,
  columns,
  logo,
  title = "Inventory Report",
  companyName = "LEELA HONDA PVT. LTD.",
  subtitle = "Inventory Management System",
  fileName = "LeelaHonda_Inventory_Report.pdf",
}) => {
  const doc = new jsPDF("landscape", "mm", "a4");

  // Header
  doc.addImage(logo, "PNG", 10, 6, 30, 25);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(companyName, 40, 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(subtitle, 40, 23);

  doc.setDrawColor(15, 23, 42);
  doc.setLineWidth(0.5);
  doc.line(12, 32, 285, 32);

  // Report info
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(12, 36, 273, 22, 2, 2, "F");

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");

  doc.text("Report", 18, 44);
  doc.text("Generated On", 90, 44);
  doc.text("Generated By", 170, 44);
  doc.text("Total Records", 240, 44);

  doc.setFont("helvetica", "normal");

  doc.text(title, 18, 51);
  doc.text(new Date().toLocaleString(), 90, 51);
  doc.text("Administrator", 170, 51);
  doc.text(String(data.length), 248, 51);

  // Table
  autoTable(doc, {
    startY: 65,

    head: [
      columns.map((column) => column.header),
    ],

    body: data.map((item) =>
      columns.map((column) => {
        if (typeof column.value === "function") {
          return column.value(item);
        }

        return item[column.value] ?? "";
      })
    ),

    theme: "grid",

    styles: {
      font: "helvetica",
      fontSize: 8,
      cellPadding: 2.5,
      overflow: "linebreak",
      valign: "middle",
    },

    headStyles: {
      fillColor: [15, 23, 42],
      textColor: 255,
      halign: "center",
      fontStyle: "bold",
    },

    bodyStyles: {
      textColor: [60, 60, 60],
    },

    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },

    columnStyles: Object.fromEntries(
      columns.map((column, index) => [
        index,
        {
          cellWidth: column.width,
          halign: column.align || "left",
        },
      ])
    ),

    margin: {
      left: 12,
      right: 12,
    },

    didDrawPage: () => {
      const pageSize = doc.internal.pageSize;
      const pageHeight = pageSize.height;
      const pageWidth = pageSize.width;

      doc.setDrawColor(220);
      doc.line(
        12,
        pageHeight - 12,
        pageWidth - 12,
        pageHeight - 12
      );

      doc.setFontSize(9);
      doc.setTextColor(120);

      doc.text(
        "Generated by Leela Honda Inventory Management System",
        12,
        pageHeight - 6
      );

      doc.text(
        `Page ${doc.getNumberOfPages()}`,
        pageWidth - 25,
        pageHeight - 6
      );
    },
  });

  doc.save(fileName);
};